### ISSUE TITLE
Utilize a new library: jQueryflexdatalist

### ISSUE THREAD

**Issue by jlp0328** [matthewglassman/projectrecipe#13]
http://projects.sergiodinislopes.pt/flexdatalist/

DATA FROM REMOTE FILE with Multiple Values

**HTML**
<input type='text'
       placeholder='Write your country name'
       class='flexdatalist'
       data-data='countries.json'
       data-search-in='name'
       data-visible-properties='["name","capital","continent"]'
       data-selection-required='true'
       data-value-property='id'
       data-text-property='{capital}, {name}, {continent}'
       data-min-length='1'
       multiple='multiple'
       name='country_id_3'>

**JavaScript**

$('.flexdatalist').flexdatalist({
     minLength: 1,
     textProperty: '{capital}, {name}, {continent}',
     valueProperty: 'id',
     selectionRequired: true,
     visibleProperties: ["name","capital","continent"],
     searchIn: 'name',
     data: 'countries.json'
});

**Comment by jlp0328** [comment]
<input type='text'
       placeholder='Write your country name'
       class='flexdatalist'
       data-data='countries.json'
       data-search-in='name'
       data-visible-properties='["name","capital","continent"]'
       data-selection-required='true'
       data-value-property='id'
       data-text-property='{capital}, {name}, {continent}'
       data-min-length='1'
       multiple='multiple'
       name='country_id_3'>

**Comment by kathleenzee** [comment]
worked on it tonight.
