### ISSUE TITLE
Capture Data (user and recipes searched) to Firebase

### ISSUE THREAD

**Issue by matthewglassman** [matthewglassman/projectrecipe#14]

**Comment by jlp0328** [comment]
Goal of Database:

Username,  Add button on recipe card for user to save recipe to their database

**Comment by matthewglassman** [comment]
In short order.. 
Upon hitting landing page.. 

- User will see form for entering email and password with Sign Up and Login Button
- User will enter email and password
- If email and password do not exist in firebase authentication, user can click sign up instead and email and password will automatically be stored in database authentication.
- If email DOES exist and user clicks login button, user is taken to their page with saved recipes being pulled and shown somewhere and the ability to enter new ingredient search.
- Upon login, the login and signup buttons hide and the signout button appears.

**Comment by matthewglassman** [comment]
Can capture data, but am having trouble pulling it back out of database.  Right now going to put it on hold and try to focus my efforts on core work that still needs to be done.

**Comment by matthewglassman** [comment]
Can use the following to gather and display any items that contain a certain email address to console, but am unsure about how to make that item a variable in the equalTo part or involve it in an If statement.

```database.ref().orderByChild('User').equalTo('matthew@bootcamp.com').on("value", function(snapshot) { for (var key in snapshot.val()){ console.log(snapshot.val()[key].User); console.log(snapshot.val()[key].number); }; });```
