### ISSUE TITLE
Front End:Update Spoonacular API with Search Parameters

### ISSUE THREAD

**Issue by matthewglassman** [matthewglassman/projectrecipe#17]

**Comment by georgejincy** [comment]
function escapeEmailAddress(email) {
  if (!email) return false

  // Replace '.' (not allowed in a Firebase key) with ',' (not allowed in an email address)
  email = email.toLowerCase();
  email = email.replace(/\./g, ',');
  return email;
}

**Comment by kathleenzee** [comment]
update in jincy.js
@georgejincy to send kz example that is helpful

**Comment by georgejincy** [comment]
Here is an example: 
function escapeEmailAddress(email) {
if (!email) return false

// Replace '.' (not allowed in a Firebase key) with ',' (not allowed in an email address)
email = email.toLowerCase();
email = email.replace(/./g, ',');
return email;
}
