### ISSUE TITLE
Validate the check for "undefined" in the function extractRecipeInfo

### ISSUE THREAD

**Issue by georgejincy** [matthewglassman/projectrecipe#36]
the check does not seem to be working
if (recipeResults[i].sourceName === "undefined" || recipeResults[i].sourceName === " " ) {
                        RecipeInfo.creditText = errMsg;
                }else{
                    RecipeInfo.creditText = recipeResults[i].sourceName;
                }
Eg: Title: Unfried" Chicken
appdemo.js:39 Cooking minutes: 55
appdemo.js:47 Credit text: **undefined**
appdemo.js:91 Ingredients: 
appdemo.js:93 6 chicken
appdemo.js:91 Ingredients: 
appdemo.js:93 1 egg
appdemo.js:93 1cup corn flake

**Comment by kathleenzee** [comment]
fixxed this issue for all types in the function.
 if (typeof(recipeResults[i].sourceName) === "undefined" || recipeResults[i].sourceName === " " ) {
                        console.log("%csourceName was undefined", 'background: #222; color: #bada55')
                        RecipeInfo.creditText = errMsg;
                }else{
                    RecipeInfo.creditText = recipeResults[i].sourceName;
                }
